spring.application.name=oracle-crud-demo
# Oracle Connection Settings
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.username=my_developer
spring.datasource.password=SecurePass789
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate Configurations
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
